services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - '8761:8761' 
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 4
  config-service:
    build: ./config-service
    container_name: config-service
    ports: 
      - '9999:9999'
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:9999/actuator/health"]
      interval: 10s
      retries: 4
    environment: 
      - DISCOVERY_URL=http://discovery-service:8761/eureka
    depends_on:
      discovery-service:
        condition: service_healthy
  customer-service: 
    build: ./customer-service
    container_name: customer-service
    ports:
      - '8081:8081'
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8081/actuator/health"]
      interval: 10s
      retries: 4
    depends_on:
      config-service:  	
        condition: service_healthy
    environment:
      - DISCOVERY_URL=http://discovery-service:8761/eureka 
      - CONFIG_URL=http://config-service:9999
  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - '8082:8082'
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8082/actuator/health"]
      interval: 10s
      retries: 4
    depends_on: 
      config-service:
        condition: service_healthy  
    environment:
      - CONFIG_URL=http://config-service:9999
      - DISCOVERY_URL=http://discovery-service:8761/eureka
  billing-service:
    build: ./billing-service
    container_name: billing-service
    ports:
      - '8083:8083'
    depends_on:
      customer-service:
        condition: service_healthy
      inventory-service:
        condition: service_healthy
    environment:
      - CONFIG_URL=http://config-service:9999
      - DISCOVERY_URL=http://discovery-service:8761/eureka
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - '8888:8888'
    depends_on:
      config-service:
        condition: service_healthy
    environment:
      - CONFIG_URL=http://config-service:9999
      - DISCOVERY_URL=http://discovery-service:8761/eureka